const articles = [
    {
        id: 1,
        name: 'Shitsu',
        description: 'Lorem ipsum dolor',
        image: 'images/shitsu-1.jpg',
        category: 'shitsu',
    },
    {
        id: 2,
        name: 'Shitsu',
        description: 'Lorem ipsum dolor sit amet',
        image: 'images/shitsu-2.jpg',
        category: 'shitsu',
        ishome: 'true',
    },
    {
        id: 3,
        name: 'Shitsu',
        description: 'Lorem ipsum dolor sit amet ab nemo quis!',
        image: 'images/shitsu-3.jpg',
        category: 'shitsu',
    },
    {
        id: 4,
        name: 'Lapdog',
        description: 'Lorem ipsum dolor sit amet ab nemo quis!',
        image: 'images/lapdog-1.jpg',
        category: 'lapdog',
        ishome: 'true',
    },
    {
        id: 5,
        name: 'Lapdog',
        description: 'Lorem ipsum dolor sit amet ab nemo quis!',
        image: 'images/lapdog-2.jpg',
        category: 'lapdog',
    },
    {
        id: 6,
        name: 'Lapdog',
        description: 'Lorem ipsum dolor sit amet ab nemo quis!',
        image: 'images/lapdog-3.jpg',
        category: 'lapdog',
    },
    {
        id: 7,
        name: 'Yorkshire Terrier',
        description: 'Lorem ipsum dolor sit amet ab nemo quis!',
        image: 'images/yorkshire-terrier-1.jpg',
        category: 'yorkshire',
        ishome: 'true',
    },
    {
        id: 8,
        name: 'Yorkshire Terrier',
        description: 'Lorem ipsum dolor sit amet ab nemo quis!',
        image: 'images/yorkshire-terrier-2.jpg',
        category: 'yorkshire',
    },
    {
        id: 9,
        name: 'Yorkshire Terrier',
        description: 'Lorem ipsum dolor sit amet ab nemo quis!',
        image: 'images/yorkshire-terrier-3.jpg',
        category: 'yorkshire',
    },
]

export default articles
